#! /bin/sh

PRIMARY_MONITOR_NAME='HDMI-A-0'
SECOND_MONITOR_NAME='DisplayPort-2'
SECOND_MONITOR_CONNECTED=$(xrandr -q | grep "${SECOND_MONITOR_NAME} connected")

xrandr --output $PRIMARY_MONITOR_NAME --primary --mode 2560x1440 --rate 59.95 &
if [[ $SECOND_MONITOR_CONNECTED ]]; then
  xrandr --output $SECOND_MONITOR_NAME --mode 5120x1440 --rate 59.98 --right-of $PRIMARY_MONITOR_NAME &
fi
xset r rate 250 25 &
xsetroot -cursor_name left_ptr
~/.fehbg &
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
picom --config ~/.config/picom/picom -b &
qpwgraph -a -x -m &
solaar -w hide &

bspc monitor $PRIMARY_MONITOR_NAME -d I II III IV
if [[ $SECOND_MONITOR_CONNECTED ]]; then
  bspc monitor $SECOND_MONITOR_NAME -d V
fi

bspc config border_width         2
bspc config border_radius       10
bspc config focused_border_color \#7da6ff
bspc config window_gap          8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
