#! /bin/sh

xrandr --output HDMI-A-0 --mode 2560x1440 --rate 120 &
xset r rate 200 25 &
~/.fehbg &
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
picom --config ~/.config/picom/picom -b

bspc monitor -d I II III IV

bspc config border_width         2
bspc config border_radius       10
bspc config focused_border_color \#7da6ff
bspc config window_gap          8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
